apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazurde-sf-deployment
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lazurde-sf
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lazurde-sf
    spec:
      nodeSelector:
        node: compute-optimized 
      containers:
      - image: 592826755224.dkr.ecr.us-east-2.amazonaws.com/IMAGE_REPO_NAME:IMAGE_TAG
        command: ["bash", "-c", "COMMAND"]
        imagePullPolicy: Always
        name: lazurde-sf
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: CPU_LIMITS
            memory: MEM_LIMITS
          requests:
            cpu: CPU_REQ
            memory: MEM_REQ