export const contactCards: any = {
  "en-sa": [
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "Sunday to Thursday 9:00 amto 5:00 pm",
      cardTitle: "Call Us",
      phone: "9200 09709",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "Sunday to Thursday 9:00 amto 5:00 pm",
      cardTitle: "Contact Email",
      phone: "",
      vatNumber: "",
      buttonText: "",
      email: "info@lazurde.com",
    },
    {
      show_whatsapp_btn: true,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "Sunday to Thursday 9:00 amto 5:00 pm",
      cardTitle: "WhatsApp",
      phone: "+966553561501",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "You can chat with us by clicking “Chat Now” below",
      cardTitle: "Chat with us",
      phone: "+966553561501",
      vatNumber: "",
      buttonText: "Chat",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText:
        "You can e-mail us your query or any feedback (positive or negative) by clicking",
      cardTitle: "Send Feedback",
      phone: "",
      vatNumber: "",
      buttonText: "Feedback",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "CR Number: 1010221531",
      imgLink: null,
      cardLink: null,
      cardText:
        "L‘azurde Jewelry Al Masaref Street 198 Banks District Riyadh 11521 Saudi Arabia",
      cardTitle: "Lazurde KSA HQ",
      phone: "Telephone : +966920009709",
      vatNumber: "VAT Number: 300054684710003",
      buttonText: "",
      email: "",
    },
  ],
  "ar-sa": [
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "من الأحد إلى الخميس من الساعة 9:00 صباحًا حتى 5:00 مساءً",
      cardTitle: "اتصل بنا",
      phone: "9200 09709",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "من الأحد إلى الخميس من الساعة 9:00 صباحًا حتى 5:00 مساءً",
      cardTitle: "تواصل بالبريد الاكتروني",
      phone: "",
      vatNumber: "",
      buttonText: "",
      email: "info@lazurde.com",
    },
    {
      show_whatsapp_btn: true,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "من الأحد إلى الخميس من الساعة 9:00 صباحًا حتى 5:00 مساءً",
      cardTitle: "واتس اب",
      phone: "+966553561501",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: 'يمكنك الدردشة معنا من خلال النقر على "الدردشة الآن" أدناه',
      cardTitle: "دردش معنا",
      phone: "+966553561501",
      vatNumber: "",
      buttonText: "محادثة",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText:
        "يمكنك مراسلتنا عبر البريد الإلكتروني استفسارك أو أي ملاحظات (إيجابية أو سلبية) من خلال النقر",
      cardTitle: "ارسل رأيك",
      phone: "",
      vatNumber: "",
      buttonText: "تعليق",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "رقم السجل التجاري: 1010221531",
      imgLink: null,
      cardLink: null,
      cardText:
        "مجوهرات لازوردي شارع المصارف 198 حى البنوك الرياض 11521 المملكة العربية السعودية",
      cardTitle: "لازوردي المملكة العربية السعودية HQ",
      phone: "+966920009709",
      phoneHeading: " :هاتف",
      vatNumber: "الرقم الضريبي: 300054684710003",
      buttonText: "",
      email: "",
    },
  ],
  "en-ae": [
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "Monday to Friday,  from 9am - 5 pm",
      cardTitle: "Call Us",
      phone: "80064775",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "Monday to Friday,  from 9am - 5 pm",
      cardTitle: "Contact Email",
      phone: "",
      vatNumber: "",
      buttonText: "",
      email: "info@lazurde.com",
    },
    // {
    //   show_whatsapp_btn: true,
    //   crNumber: "",
    //   imgLink: null,
    //   cardLink: null,
    //   cardText: "Monday to Friday 9:30 am to 5:30 pm",
    //   cardTitle: "WhatsApp",
    //   phone: "+966553561501",
    //   vatNumber: "",
    //   buttonText: "",
    //   email: "",
    // },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "You can chat with us by clicking “Chat Now” below",
      cardTitle: "Chat with us",
      phone: "80064775",
      vatNumber: "",
      buttonText: "Chat",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText:
        "You can e-mail us your query or any feedback (positive or negative) by clicking",
      cardTitle: "Send Feedback",
      phone: "",
      vatNumber: "",
      buttonText: "Feedback",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "CR Number: 1010221531",
      imgLink: null,
      cardLink: null,
      cardText:
        "HQ - P.O.Box 60843, Dubai, Deira, Gold Souk, Gold Land Building, Office No 313",
      cardTitle: "Lazurde UAE HQ",
      phone: "Telephone : +97180064775",
      vatNumber: "VAT Number: 300054684710003",
      buttonText: "",
      email: "",
    },
  ],
  "ar-ae": [
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "من يوم الأتنين إلى يوم الجمعه 9 صباحًا حتى 5 مساءً",
      cardTitle: "اتصل بنا",
      phone: "80064775",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "من يوم الأتنين إلى يوم الجمعه 9 صباحًا حتى 5 مساءً",
      cardTitle: "تواصل بالبريد الاكتروني",
      phone: "",
      vatNumber: "",
      buttonText: "",
      email: "info@lazurde.com",
    },
    // {
    //   show_whatsapp_btn: true,
    //   crNumber: "",
    //   imgLink: null,
    //   cardLink: null,
    //   cardText: "من الأحد إلى الخميس من 9:30 صباحًا إلى 5:30 مساءً",
    //   cardTitle: "واتس اب",
    //   phone: "+966553561501",
    //   vatNumber: "",
    //   buttonText: "",
    //   email: "",
    // },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: 'يمكنك الدردشة معنا من خلال النقر على "الدردشة الآن" أدناه',
      cardTitle: "دردش معنا",
      phone: "80064775",
      vatNumber: "",
      buttonText: "محادثة",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText:
        "يمكنك مراسلتنا عبر البريد الإلكتروني استفسارك أو أي ملاحظات (إيجابية أو سلبية) من خلال النقر",
      cardTitle: "ارسل رأيك",
      phone: "",
      vatNumber: "",
      buttonText: "تعليق",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "رقم السجل التجاري: 1010221531",
      imgLink: null,
      cardLink: null,
      cardText:
        "المقر الرئيسي - ص.ب 60843، دبي، ديرة، سوق الذهب، مبنى أرض الذهب، مكتب رقم 313",
      cardTitle: "لازوردي المملكة الإمارات العربية المتحدة HQ",
      phone: "+97180064775",
      phoneHeading: " :هاتف",
      vatNumber: "الرقم الضريبي: 300054684710003",
      buttonText: "",
      email: "",
    },
  ],
  "en-eg": [
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "All week Days from 9am to 9 pm",
      cardTitle: "Call Us",
      phone: "16802",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "All week Days from 9am to 9 pm",
      cardTitle: "Contact Email",
      phone: "",
      vatNumber: "",
      buttonText: "",
      email: "info@lazurde.com",
    },
    {
      show_whatsapp_btn: true,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "All week Days from 9am to 9 pm",
      cardTitle: "WhatsApp",
      phone: "+20 121 277 7725",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "You can chat with us by clicking “Chat Now” below",
      cardTitle: "Chat with us",
      phone: "+201212777725",
      vatNumber: "",
      buttonText: "Chat",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText:
        "You can e-mail us your query or any feedback (positive or negative) by clicking",
      cardTitle: "Send Feedback",
      phone: "",
      vatNumber: "",
      buttonText: "Feedback",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "CR Number: 1010221531",
      imgLink: null,
      cardLink: null,
      cardText: "1st Industrial Zone - Al Obour City - Cairo, Egypt",
      cardTitle: "Lazurde Egypt HQ",
      phone: "Telephone : 16802",
      vatNumber: "VAT Number: 300054684710003",
      buttonText: "",
      email: "",
    },
  ],
  "ar-eg": [
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "جميع أيام الأسبوع من الساعة 9 صباحًا حتى 9 مساءً",
      cardTitle: "اتصل بنا",
      phone: "16802",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "جميع أيام الأسبوع من الساعة 9 صباحًا حتى 9 مساءً",
      cardTitle: "تواصل بالبريد الاكتروني",
      phone: "",
      vatNumber: "",
      buttonText: "",
      email: "info@lazurde.com",
    },
    {
      show_whatsapp_btn: true,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: "جميع أيام الأسبوع من الساعة 9 صباحًا حتى 9 مساءً",
      cardTitle: "واتس اب",
      phone: "+20 121 277 7725",
      vatNumber: "",
      buttonText: "",
      email: "",
    },
    {
      hideThisBlock: true,
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText: 'يمكنك الدردشة معنا من خلال النقر على "الدردشة الآن" أدناه',
      cardTitle: "دردش معنا",
      phone: "+201212777725",
      vatNumber: "",
      buttonText: "محادثة",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "",
      imgLink: null,
      cardLink: null,
      cardText:
        "يمكنك مراسلتنا عبر البريد الإلكتروني استفسارك أو أي ملاحظات (إيجابية أو سلبية) من خلال النقر",
      cardTitle: "ارسل رأيك",
      phone: "",
      vatNumber: "",
      buttonText: "تعليق",
      email: "",
    },
    {
      show_whatsapp_btn: false,
      crNumber: "رقم السجل التجاري: 1010221531",
      imgLink: null,
      cardLink: null,
      cardText: "المنطقة الصناعية الأولى - مدينة العبور - القاهرة، مصر",
      cardTitle: "لازوردي المملكة مصر HQ",
      phone: "16802",
      phoneHeading: " :هاتف",
      vatNumber: "الرقم الضريبي: 300054684710003",
      buttonText: "",
      email: "",
    },
  ],
};
