import {
  Component,
  initialize,
  Pagination,
  Reference,
} from "@bloomreach/spa-sdk";
import { ServerResponse } from "http";
import axios from "axios";
import { plpUrls, staticPagesUrls } from "./websiteUrls";

function flatten(array?: Component[]): Component[] {
  if (!array) {
    return [];
  }

  const flattenedArray: Component[] = [];

  for (const element of array) {
    flattenedArray.push(element);
    const children = element.getChildren();
    if (Array.isArray(children)) {
      flattenedArray.push(...flatten(children));
    }
  }

  return flattenedArray;
}

export const setSitemapXML = async (
  response?: ServerResponse,
  endpoint?: string,
  path?: string,
  namespaceCheck?: string,
  locale?: string,
  req?: any
) => {
  if (response) {
    const configuration = {
      path,
      endpoint: endpoint,
    };
    const protocol = "https";
    const host = req?.headers["x-forwarded-host"] || req?.headers.host;
    const BASE_URL = `${protocol}://${host}`;
    const page = await initialize({ ...configuration, httpClient: axios });
    const urls: Component = flatten(page?.getComponent().getChildren()).find(
      (component) => component?.getName() === "urlset"
    );
    if (namespaceCheck && urls?.getId() !== namespaceCheck) {
      console.warn(
        "namespace ids does not match up: ",
        urls?.getId(),
        namespaceCheck
      );
    }
    const pagination = page?.getContent<Pagination>(
      urls.getModels<{ pagination: Reference }>().pagination
    );

    const urlEntries = pagination
      ?.getItems()
      .filter(
        (item) =>
          !page.getContent(item)?.getData<any>()?.metasitemapxml?.exclude
      )
      .map((item) => {
        const content = page?.getContent(item);
        const getURL = content?.getUrl();
        const maxURLsPerSitemap = 50000;
        const pageUrls = divideURLsIntoSitemaps(getURL, maxURLsPerSitemap);
        const data = content?.getData<any>();
        const lastModified: Date | undefined =
          data?.metasitemapxml?.lastmod &&
          new Date(data?.metasitemapxml?.lastmod);
        const priority = data?.metasitemapxml?.priority || 0.8;
        return {
          url: `${BASE_URL}/${locale}${pageUrls}`,
          priority: priority,
          lastModified: lastModified?.toISOString() || new Date().toISOString(),
        };
      });

    const plpUrlsForSiteMap = plpUrls?.map((url) => {
      return {
        url: `${BASE_URL}${url}`,
        priority: 0.9,
        lastModified: new Date().toISOString(),
      };
    });

    const regionBasePlps = plpUrlsForSiteMap?.filter((item) =>
      item?.url?.includes(locale)
    );

    const staticPages = staticPagesUrls?.map((page) => {
      return {
        url: `${BASE_URL}/${locale}${page?.url}`,
        priority: page?.priority || 0.7,
        lastModified: page?.lastModified,
      };
    });

    const excludedUrls = [
      "https://www.lazurde.com/en-sa/lazurde",
      "https://www.lazurde.com/ar-sa/lazurde",
      "https://www.lazurde.com/en-ae/lazurde",
      "https://www.lazurde.com/ar-ae/lazurde",
      "https://www.lazurde.com/en-eg/lazurde",
      "https://www.lazurde.com/ar-eg/lazurde",
      "https://www.lazurde.com/en-sa/jewelry",
      "https://www.lazurde.com/ar-sa/jewelry",
      "https://www.lazurde.com/en-ae/jewelry",
      "https://www.lazurde.com/ar-ae/jewelry",
      "https://www.lazurde.com/en-eg/jewelry",
      "https://www.lazurde.com/ar-eg/jewelry",
      "https://www.lazurde.com/en-sa/gifts-occasions/lazurde",
      "https://www.lazurde.com/ar-sa/gifts-occasions/lazurde",
      "https://www.lazurde.com/en-ae/gifts-occasions/lazurde",
      "https://www.lazurde.com/ar-ae/gifts-occasions/lazurde",
      "https://www.lazurde.com/en-eg/gifts-occasions/lazurde",
      "https://www.lazurde.com/ar-eg/gifts-occasions/lazurde",
      "https://www.lazurde.com/en-sa/fashion-jewelry/gold-plated",
      "https://www.lazurde.com/en-sa/fashion-jewelry/kids",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/4000-above",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/white-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/new-in",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/1000-2000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/shop-all",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/rose-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/special-price",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/best-sellers",
      "https://www.lazurde.com/en-sa/fashion-jewelry/half-sets",
      "https://www.lazurde.com/en-sa/fashion-jewelry/sterling-silver",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/500-1000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/2000-4000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/multicolor-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/pearls",
      "https://www.lazurde.com/en-sa/fashion-jewelry/mens",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/under-500",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/diamonds",
      "https://www.lazurde.com/en-sa/miss-l/missl-footer",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/colored-stones",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/kids/yellow-gold",
      "https://www.lazurde.com/en-sa/gold/shop-all",
      "https://www.lazurde.com/en-sa/collection",
      "https://www.lazurde.com/en-sa/jewelry/shop-all",
      "https://www.lazurde.com/en-sa/love-engagement/shop-all",
      "https://www.lazurde.com/en-sa/gift-occasions/shop-all",
      "https://www.lazurde.com/en-sa/help-centre/refund-and-return",
      "https://www.lazurde.com/en-sa/index",
      "https://www.lazurde.com/en-sa/account-success",
      "https://www.lazurde.com/en-sa/",
      "https://www.lazurde.com/en-sa/lab-grown-diamonds/shop-all",
      "https://www.lazurde.com/en-sa/diamond/shop-all",
      "https://www.lazurde.com/en-sa/index",
      "https://www.lazurde.com/en-sa/",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/rose-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/500-1000",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/gold-plated",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/half-sets",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/1000-2000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/diamonds",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/pearls",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/kids",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/colored-stones",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/new-in",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/multicolor-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/pearls",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/white-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/2000-4000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/under-500",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/4000-above",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/special-price",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/4000-above",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/4000-above",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/yellow-gold",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/sterling-silver",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/best-sellers",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/multicolor-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/white-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/new-in",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/500-1000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/colored-stones",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/shop-all",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/mens",
      "https://www.lazurde.com/ar-sa/miss-l/missl-footer",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/rose-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/diamonds",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/best-sellers",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/2000-4000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/special-price",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/1000-2000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/under-500",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/kids/yellow-gold",
      "https://www.lazurde.com/en-eg//gifts-occasions/miss-l",
      "https://www.lazurde.com/en-eg//love-engagement/miss-l",
      "https://www.lazurde.com/en-eg/miss-l/gold-friday",
      "https://www.lazurde.com/en-eg/fashion-jewelry/4000-8000",
      "https://www.lazurde.com/en-eg/fashion-jewelry/10000-above",
      "https://www.lazurde.com/en-eg/fashion-jewelry/8000-10000",
      "https://www.lazurde.com/en-eg/fashion-jewelry/under-2000",
      "https://www.lazurde.com/en-eg/miss-l/missl-footer",
      "https://www.lazurde.com/ar-eg/miss-l/gold-friday",
      "https://www.lazurde.com/ar-eg//gifts-occasions/miss-l",
      "https://www.lazurde.com/ar-eg//love-engagement/miss-l",
      "https://www.lazurde.com/ar-eg//love-engagement/lazurde",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/under-2000",
      "https://www.lazurde.com/ar-eg/miss-l/missl-footer",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/under-500",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/white-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/2000-4000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/500-1000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/best-sellers",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/special-price",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/pearls",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/yellow-gold",
      "https://www.lazurde.com/en-ae/fashion-jewelry/kids",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/new-in",
      "https://www.lazurde.com/en-ae/fashion-jewelry/gold-plated",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/1000-2000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/colored-stones",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/multicolor-gold",
      "https://www.lazurde.com/en-ae/fashion-jewelry/sterling-silver",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/rose-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/diamonds",
      "https://www.lazurde.com/en-ae/fashion-jewelry/half-sets",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/4000-above",
      "https://www.lazurde.com/en-ae/fashion-jewelry/mens",
      "https://www.lazurde.com/en-ae/miss-l/missl-footer",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/kids/shop-all",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/shop-all",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/special-price",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/4000-above",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/sterling-silver",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/half-sets",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/under-500",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/multicolor-gold",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/white-gold",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/gold-plated",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/yellow-gold",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/2000-4000",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/500-1000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/under-500",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/pearls",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/multicolor-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/new-in",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/pearls",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/yellow-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/rose-gold",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/mens",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/1000-2000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/white-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/4000-above",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/rose-gold",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/colored-stones",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/special-price",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/1000-2000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/500-1000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/best-sellers",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/2000-4000",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/diamonds",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/diamonds",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/kids",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/colored-stones",
      "https://www.lazurde.com/ar-ae/miss-l/missl-footer",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/shop-all",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/kids/shop-all",
      "https://www.lazurde.com/en-eg/fashion-jewelry/necklaces-pendants",
      "https://www.lazurde.com/en-eg/fashion-jewelry/rings",
      "https://www.lazurde.com/en-eg/fashion-jewelry/bracelets-anklets",
      "https://www.lazurde.com/en-eg/fashion-jewelry/earrings",
      "https://www.lazurde.com/en-eg/fashion-jewelry/sets",
      "https://www.lazurde.com/en-eg/fashion-jewelry/shop-all",
      "https://www.lazurde.com/en-eg/fashion-jewelry/best-sellers",
      "https://www.lazurde.com/en-eg/fashion-jewelry/new-in",
      "https://www.lazurde.com/en-eg/fashion-jewelry/special-price",
      "https://www.lazurde.com/en-eg/fashion-jewelry/yellow-gold",
      "https://www.lazurde.com/en-eg/fashion-jewelry/white-gold",
      "https://www.lazurde.com/en-eg/fashion-jewelry/rose-gold",
      "https://www.lazurde.com/en-eg/fashion-jewelry/multicolor-gold",
      "https://www.lazurde.com/en-eg/fashion-jewelry/diamonds",
      "https://www.lazurde.com/en-eg/fashion-jewelry/colored-stones",
      "https://www.lazurde.com/en-eg/fashion-jewelry/pearls",
      "https://www.lazurde.com/en-eg/fashion-jewelry/under-500",
      "https://www.lazurde.com/en-eg/fashion-jewelry/500-1000",
      "https://www.lazurde.com/en-eg/fashion-jewelry/1000-2000",
      "https://www.lazurde.com/en-eg/fashion-jewelry/2000-4000",
      "https://www.lazurde.com/en-eg/fashion-jewelry/4000-above",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/necklaces-pendants",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/rings",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/bracelets-anklets",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/earrings",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/sets",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/shop-all",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/best-sellers",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/new-in",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/special-price",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/yellow-gold",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/white-gold",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/rose-gold",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/multicolor-gold",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/diamonds",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/colored-stones",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/pearls",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/under-500",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/500-1000",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/1000-2000",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/2000-4000",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/4000-8000",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/8000-10000",
      "https://www.lazurde.com/ar-eg/fashion-jewelry/10000-above",
      "https://www.lazurde.com/en-sa/fashion-jewelry/necklaces-pendants",
      "https://www.lazurde.com/en-sa/fashion-jewelry/rings",
      "https://www.lazurde.com/en-sa/fashion-jewelry/bracelets-anklets",
      "https://www.lazurde.com/en-sa/fashion-jewelry/earrings",
      "https://www.lazurde.com/en-sa/fashion-jewelry/sets",
      "https://www.lazurde.com/en-sa/fashion-jewelry/shop-all",
      "https://www.lazurde.com/en-sa/fashion-jewelry/best-sellers",
      "https://www.lazurde.com/en-sa/fashion-jewelry/new-in",
      "https://www.lazurde.com/en-sa/fashion-jewelry/special-price",
      "https://www.lazurde.com/en-sa/fashion-jewelry/yellow-gold",
      "https://www.lazurde.com/en-sa/fashion-jewelry/white-gold",
      "https://www.lazurde.com/en-sa/fashion-jewelry/rose-gold",
      "https://www.lazurde.com/en-sa/fashion-jewelry/multicolor-gold",
      "https://www.lazurde.com/en-sa/fashion-jewelry/diamonds",
      "https://www.lazurde.com/en-sa/fashion-jewelry/colored-stones",
      "https://www.lazurde.com/en-sa/fashion-jewelry/pearls",
      "https://www.lazurde.com/en-sa/fashion-jewelry/under-500",
      "https://www.lazurde.com/en-sa/fashion-jewelry/500-1000",
      "https://www.lazurde.com/en-sa/fashion-jewelry/1000-2000",
      "https://www.lazurde.com/en-sa/fashion-jewelry/2000-4000",
      "https://www.lazurde.com/en-sa/fashion-jewelry/4000-above",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/necklaces-pendants",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/rings",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/bracelets-anklets",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/earrings",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/sets",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/shop-all",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/best-sellers",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/new-in",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/special-price",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/yellow-gold",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/white-gold",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/rose-gold",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/multicolor-gold",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/diamonds",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/colored-stones",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/pearls",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/under-500",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/500-1000",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/1000-2000",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/2000-4000",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/4000-8000",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/8000-10000",
      "https://www.lazurde.com/ar-sa/fashion-jewelry/10000-above",
      "https://www.lazurde.com/en-ae/fashion-jewelry/necklaces-pendants",
      "https://www.lazurde.com/en-ae/fashion-jewelry/rings",
      "https://www.lazurde.com/en-ae/fashion-jewelry/bracelets-anklets",
      "https://www.lazurde.com/en-ae/fashion-jewelry/earrings",
      "https://www.lazurde.com/en-ae/fashion-jewelry/sets",
      "https://www.lazurde.com/en-ae/fashion-jewelry/shop-all",
      "https://www.lazurde.com/en-ae/fashion-jewelry/best-sellers",
      "https://www.lazurde.com/en-ae/fashion-jewelry/new-in",
      "https://www.lazurde.com/en-ae/fashion-jewelry/special-price",
      "https://www.lazurde.com/en-ae/fashion-jewelry/yellow-gold",
      "https://www.lazurde.com/en-ae/fashion-jewelry/white-gold",
      "https://www.lazurde.com/en-ae/fashion-jewelry/rose-gold",
      "https://www.lazurde.com/en-ae/fashion-jewelry/multicolor-gold",
      "https://www.lazurde.com/en-ae/fashion-jewelry/diamonds",
      "https://www.lazurde.com/en-ae/fashion-jewelry/colored-stones",
      "https://www.lazurde.com/en-ae/fashion-jewelry/pearls",
      "https://www.lazurde.com/en-ae/fashion-jewelry/under-500",
      "https://www.lazurde.com/en-ae/fashion-jewelry/500-1000",
      "https://www.lazurde.com/en-ae/fashion-jewelry/1000-2000",
      "https://www.lazurde.com/en-ae/fashion-jewelry/2000-4000",
      "https://www.lazurde.com/en-ae/fashion-jewelry/4000-above",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/necklaces-pendants",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/rings",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/bracelets-anklets",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/earrings",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/sets",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/shop-all",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/best-sellers",
      "https://www.lazurde.com/ar-ae/fashion-jewelry/new-in",
      "https://www.lazurde.com/en-eg/fashion-jewelry/special-price",
      "https://www.lazurde.com/en-eg/fashion-jewelry/yellow-gold",
      "https://www.lazurde.com/en-eg/fashion-jewelry/white-gold",
      "https://www.lazurde.com/en-eg/fashion-jewelry/rose-gold",
      "https://www.lazurde.com/en-eg/fashion-jewelry/multicolor-gold",
      "https://www.lazurde.com/en-eg/fashion-jewelry/diamonds",
      "https://www.lazurde.com/en-eg/fashion-jewelry/colored-stones",
      "https://www.lazurde.com/en-eg/fashion-jewelry/pearls",
      "https://www.lazurde.com/en-eg/fashion-jewelry/under-500",
      "https://www.lazurde.com/en-eg/fashion-jewelry/500-1000",
      "https://www.lazurde.com/en-eg/fashion-jewelry/1000-2000",
      "https://www.lazurde.com/en-eg/fashion-jewelry/2000-4000",
      "https://www.lazurde.com/en-eg/fashion-jewelry/4000-above",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/best-sellers",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/new-in",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/special-price",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/yellow-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/white-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/rose-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/multicolor-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/diamonds",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/colored-stones",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/pearls",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/under-500",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/500-1000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/1000-2000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/2000-4000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/4000-above",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/best-sellers",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/new-in",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/special-price",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/yellow-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/white-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/rose-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/multicolor-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/pearls",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/colored-stones",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/diamonds",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/under-500",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/500-1000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/1000-2000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/2000-4000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/4000-above",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/best-sellers",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/new-in",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/special-price",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/yellow-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/white-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/rose-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/multicolor-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/diamonds",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/colored-stones",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/pearls",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/under-500",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/500-1000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/1000-2000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/2000-4000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/4000-above",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/best-sellers",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/new-in",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/special-price",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/yellow-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/white-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/rose-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/under-500",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/500-1000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/1000-2000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/2000-4000",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/4000-above",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/best-sellers",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/new-in",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/special-price",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/yellow-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/white-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/rose-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/multicolor-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/diamonds",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/colored-stones",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/pearls",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/under-500",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/500-1000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/1000-2000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/2000-4000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/4000-above",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/best-sellers",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/new-in",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/special-price",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/yellow-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/shop-all",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/white-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/rose-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/multicolor-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/pearls",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/colored-stones",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/diamonds",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/under-500",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/500-1000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/1000-2000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/2000-4000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/4000-above",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/best-sellers",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/new-in",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/special-price",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/yellow-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/white-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/rose-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/under-500",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/500-1000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/1000-2000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/2000-4000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/4000-above",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/best-sellers",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/new-in",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/special-price",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/yellow-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/white-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/rose-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/multicolor-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/diamonds",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/colored-stones",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/pearls",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/under-4000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/4000-6000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/6000-8000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/8000-10000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/10000-above",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/best-sellers",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/new-in",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/special-price",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/yellow-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/white-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/rose-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/multicolor-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/pearls",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/colored-stones",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/diamonds",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/under-4000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/4000-6000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/6000-8000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/8000-10000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/10000-above",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/best-sellers",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/new-in",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/special-price",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/yellow-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/white-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/rose-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/multicolor-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/diamonds",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/colored-stones",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/pearls",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/under-4000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/4000-6000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/6000-8000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/8000-10000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/10000-above",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/under-500",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/500-1000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/1000-2000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/2000-4000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/4000-above",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/best-sellers",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/new-in",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/special-price",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/yellow-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/white-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/rose-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/multicolor-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/diamonds",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/colored-stones",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/pearls",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/under-4000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/4000-6000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/6000-8000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/8000-10000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/10000-above",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/best-sellers",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/new-in",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/special-price",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/yellow-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/white-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/rose-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/under-4000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/4000-6000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/6000-8000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/8000-10000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/10000-above",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/best-sellers",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/new-in",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/special-price",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/yellow-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/white-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/rose-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/multicolor-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/diamonds",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/colored-stones",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/pearls",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/under-4000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/4000-6000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/6000-8000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/8000-10000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/10000-above",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/under-500",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/500-1000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/1000-2000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/2000-4000",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/4000-above",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/best-sellers",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/new-in",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/special-price",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/yellow-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/white-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/rose-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/multicolor-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/diamonds",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/colored-stones",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/pearls",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/under-4000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/4000-6000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/6000-8000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/8000-10000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/10000-above",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/best-sellers",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/new-in",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/special-price",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/yellow-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/white-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/rose-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/under-4000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/4000-6000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/6000-8000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/8000-10000",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/10000-above",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/best-sellers",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/new-in",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/special-price",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/yellow-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/white-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/rose-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/multicolor-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/pearls",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/colored-stones",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/diamonds",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/under-4000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/4000-6000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/6000-8000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/8000-10000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/10000-above",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/best-sellers",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/new-in",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/special-price",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/yellow-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/white-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/rose-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/multicolor-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/diamonds",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/colored-stones",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/pearls",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/under-4000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/4000-6000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/6000-8000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/8000-10000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/10000-above",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/best-sellers",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/new-in",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/special-price",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/yellow-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/white-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/rose-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/under-4000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/4000-6000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/6000-8000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/8000-10000",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/10000-above",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/best-sellers",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/new-in",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/special-price",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/yellow-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/white-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/rose-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/multicolor-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/diamonds",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/colored-stones",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/pearls",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/under-500",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/500-1000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/1000-2000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/2000-4000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/4000-above",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/best-sellers",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/new-in",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/special-price",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/yellow-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/white-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/rose-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/multicolor-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/pearls",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/colored-stones",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/diamonds",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/under-500",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/500-1000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/1000-2000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/2000-4000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/rings/4000-above",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/best-sellers",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/new-in",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/special-price",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/yellow-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/white-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/rose-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/multicolor-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/diamonds",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/colored-stones",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/pearls",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/under-500",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/500-1000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/1000-2000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/2000-4000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/bracelets-anklets/4000-above",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/best-sellers",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/new-in",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/special-price",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/yellow-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/white-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/rose-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/under-500",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/500-1000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/1000-2000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/2000-4000",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/4000-above",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/best-sellers",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/new-in",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/special-price",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/yellow-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/white-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/rose-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/multicolor-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/diamonds",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/colored-stones",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/pearls",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/under-500",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/500-1000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/1000-2000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/2000-4000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/4000-above",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/best-sellers",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/new-in",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/special-price",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/yellow-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/white-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/rose-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/multicolor-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/pearls",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/colored-stones",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/diamonds",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/under-500",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/500-1000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/1000-2000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/2000-4000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/4000-above",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/1000-2000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/2000-4000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/necklaces-pendants/4000-above",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/best-sellers",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/new-in",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/special-price",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/yellow-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/white-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/rose-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/multicolor-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/pearls",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/colored-stones",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/diamonds",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/under-500",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/500-1000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/1000-2000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/2000-4000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/4000-above",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/best-sellers",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/new-in",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/special-price",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/yellow-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/white-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/rose-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/multicolor-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/diamonds",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/colored-stones",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/pearls",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/under-500",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/500-1000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/1000-2000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/2000-4000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/4000-above",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/best-sellers",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/new-in",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/special-price",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/yellow-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/white-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/rose-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/multicolor-gold",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/diamonds",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/colored-stones",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/pearls",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/under-500",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/500-1000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/1000-2000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/2000-4000",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/4000-above",
      "https://www.lazurde.com/ar-sa/gift-occasions/shop-all",
      "https://www.lazurde.com/ar-sa/account-success",
      "https://www.lazurde.com/ar-sa/404",
      "https://www.lazurde.com/ar-sa/gold/shop-all",
      "https://www.lazurde.com/ar-sa/love-engagement/shop-all",
      "https://www.lazurde.com/ar-sa/500",
      "https://www.lazurde.com/ar-sa/jewelry/shop-all",
      "https://www.lazurde.com/ar-sa/sitemap.xml",
      "https://www.lazurde.com/ar-sa/index",
      "https://www.lazurde.com/ar-sa/collection",
      "https://www.lazurde.com/ar-sa/diamond/shop-all",
      "https://www.lazurde.com/ar-sa/lab-grown-diamonds/shop-all",
      "https://www.lazurde.com/ar-sa/404",
      "https://www.lazurde.com/ar-sa/500",
      "https://www.lazurde.com/ar-sa/index",
      "https://www.lazurde.com/en-eg/diamond/18k-gold",
      "https://www.lazurde.com/en-eg/404",
      "https://www.lazurde.com/en-eg/500",
      "https://www.lazurde.com/en-eg//love-engagement/lazurde",
      "https://www.lazurde.com/en-eg/collection/black-friday",
      "https://www.lazurde.com/en-eg/jewelry/shop-all",
      "https://www.lazurde.com/en-eg/diamond/18k-gold",
      "https://www.lazurde.com/en-eg/lab-grown-diamonds/shop-all",
      "https://www.lazurde.com/en-eg/404",
      "https://www.lazurde.com/en-eg/account-success",
      "https://www.lazurde.com/en-eg/500",
      "https://www.lazurde.com/en-eg/about-us",
      "https://www.lazurde.com/en-eg/help-centre/refund-and-return",
      "https://www.lazurde.com/en-eg/love-engagement/shop-all",
      "https://www.lazurde.com/en-eg/love-engagement/lazurde",
      "https://www.lazurde.com/en-eg/lab-grown-diamonds",
      "https://www.lazurde.com/en-eg/gold/shop-all",
      "https://www.lazurde.com/en-eg/diamond/shop-all",
      "https://www.lazurde.com/en-eg/help-centre/payments",
      "https://www.lazurde.com/en-eg/collection",
      "https://www.lazurde.com/en-eg/contact-us",
      "https://www.lazurde.com/en-eg/gift-occasions/shop-all",
      "https://www.lazurde.com/en-eg/collection/black-friday",
      "https://www.lazurde.com/en-eg/lazurde-policies",
      "https://www.lazurde.com/en-eg/help-centre/order",
      "https://www.lazurde.com/ar-eg/404",
      "https://www.lazurde.com/ar-eg/collection/black-friday",
      "https://www.lazurde.com/ar-eg/diamond/18k-gold",
      "https://www.lazurde.com/ar-eg/500",
      "https://www.lazurde.com/ar-eg/gift-occasions/shop-all",
      "https://www.lazurde.com/ar-eg/jewelry/shop-all",
      "https://www.lazurde.com/ar-eg/404",
      "https://www.lazurde.com/ar-eg/lab-grown-diamonds/shop-all",
      "https://www.lazurde.com/ar-eg/diamond/18k-gold",
      "https://www.lazurde.com/ar-eg/account-success",
      "https://www.lazurde.com/ar-eg/500",
      "https://www.lazurde.com/ar-eg/collection",
      "https://www.lazurde.com/ar-eg/love-engagement/shop-all",
      "https://www.lazurde.com/ar-eg/gold/shop-all",
      "https://www.lazurde.com/ar-eg/diamond/shop-all",
      "https://www.lazurde.com/en-ae/404",
      "https://www.lazurde.com/en-ae/index",
      "https://www.lazurde.com/en-ae/500",
      "https://www.lazurde.com/en-ae/gift-occasions/shop-all",
      "https://www.lazurde.com/en-ae/404",
      "https://www.lazurde.com/en-ae/index",
      "https://www.lazurde.com/en-ae/newsletter",
      "https://www.lazurde.com/en-ae/account-success",
      "https://www.lazurde.com/en-ae/jewelry/shop-all",
      "https://www.lazurde.com/en-ae/diamond/shop-all",
      "https://www.lazurde.com/en-ae/collection",
      "https://www.lazurde.com/en-ae/500",
      "https://www.lazurde.com/en-ae/lab-grown-diamonds/shop-all",
      "https://www.lazurde.com/en-ae/gold/shop-all",
      "https://www.lazurde.com/en-ae/love-engagement/shop-all",
      "https://www.lazurde.com/ar-ae/500",
      "https://www.lazurde.com/ar-ae/sitemap.xml",
      "https://www.lazurde.com/ar-ae/404",
      "https://www.lazurde.com/ar-ae/diamond/shop-all",
      "https://www.lazurde.com/ar-ae/500",
      "https://www.lazurde.com/ar-ae/sitemap.xml",
      "https://www.lazurde.com/ar-ae/lab-grown-diamonds/shop-all",
      "https://www.lazurde.com/ar-ae/collection",
      "https://www.lazurde.com/ar-ae/jewelry/shop-all",
      "https://www.lazurde.com/ar-ae/account-success",
      "https://www.lazurde.com/ar-ae/gift-occasions/shop-all",
      "https://www.lazurde.com/ar-ae/404",
      "https://www.lazurde.com/ar-ae/love-engagement/shop-all",
      "https://www.lazurde.com/ar-ae/gold/shop-all",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/necklaces-pendants/shop-all",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/rings/shop-all",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/earrings/shop-all",
      "https://www.lazurde.com/ar-ae/miss-l/jewelry/bracelets-anklets/shop-all",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/necklaces-pendants/shop-all",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/rings/shop-all",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/earrings/shop-all",
      "https://www.lazurde.com/ar-sa/miss-l/jewelry/bracelets-anklets/shop-all",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/bracelets-anklets/shop-all",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/rings/shop-all",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/earrings/shop-all",
      "https://www.lazurde.com/en-eg/miss-l/jewelry/necklaces-pendants/shop-all",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/earrings/shop-all",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/rings/shop-all",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/bracelets-anklets/shop-all",
      "https://www.lazurde.com/ar-eg/miss-l/jewelry/necklaces-pendants/shop-all",
      "https://www.lazurde.com/en-sa/gold/shop-all",
      "https://www.lazurde.com/en-sa/diamond/shop-all",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/bracelets-anklets/shop-all",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/earrings/shop-all",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/necklaces-pendants/shop-all",
      "https://www.lazurde.com/en-sa/miss-l/jewelry/rings/shop-all",
      "https://www.lazurde.com/en-ae/miss-l/jewelry/earrings/shop-all",
    ];

    const modifiedUrls = urlEntries?.concat(staticPages, regionBasePlps);
    modifiedUrls.sort((a, b) => b?.priority - a?.priority);

    const filteredUrls: any = modifiedUrls.filter(
      (url: any) => !excludedUrls.includes(url?.url)
    );

    const addedUrls = new Set();
    let xmlContent = `<?xml version="1.0" encoding="UTF-8"?>
            <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`;

    const maxFileSize = 50 * 1024 * 1024;

    for (const entry of filteredUrls) {
      if (!addedUrls.has(entry?.url)) {
        // if (
        //   entry.url.includes("miss-l") ||
        //   entry.url.includes("fashion-jewelry")
        // ) {
        //   updatedUrl = "";
        // } else {
        //   updatedUrl = entry.url;
        // }
        // if (updatedUrl) {
        const urlUpdated = entry?.url?.replace(/\/$/, "");
        console.log("fdfdfdfd", urlUpdated)
        const entrySize =
          `<url>\n<loc>${urlUpdated}</loc>\n<priority>${entry?.priority}</priority>\n<changefreq>daily</changefreq>\n<lastmod>${entry?.lastModified}</lastmod>\n</url>\n`
            .length;

        if (xmlContent.length + entrySize <= maxFileSize) {
          xmlContent += `\n<url>
              <loc>${urlUpdated}</loc>
              <priority>${entry?.priority}</priority>
              <changefreq>daily</changefreq>
              <lastmod>${entry?.lastModified}</lastmod>
          </url>`;
          addedUrls.add(urlUpdated);
        } else {
          console.warn("File size limit reached");
          break;
        }
      }
    }

    xmlContent += "\n</urlset>";

    response.setHeader("Content-Type", "text/xml");
    response.write(xmlContent);
    response.end();
  }
};

function divideURLsIntoSitemaps(urls: any, maxURLsPerSitemap: any) {
  const siteMaps = [];
  for (let i = 0; i < urls?.length; i += maxURLsPerSitemap) {
    const chunk = urls?.slice(i, i + maxURLsPerSitemap);
    siteMaps.push(chunk);
  }
  return siteMaps;
}

export const setSitemapIndexXML = async (
  response: ServerResponse,
  endpoint: string,
  path: string,
  pattern: string = "sitemap/{pageNumber}/xml",
  req: any
) => {
  if (response) {
    const configuration = {
      path,
      endpoint: endpoint,
    };
    const protocol = "https";
    const host = req?.headers["x-forwarded-host"] || req?.headers.host;
    const BASE_URL = `${protocol}://${host}`;
    const page = await initialize({ ...configuration, httpClient: axios });
    const urls: Component = flatten(page?.getComponent().getChildren()).find(
      (component) => component?.getName() === "sitemap"
    );
    const pagination = page?.getContent<Pagination>(
      urls?.getModels<{ pagination: Reference }>().pagination
    );
    const sitemaps = Math.ceil(pagination?.getTotal() / 200);
    response.setHeader("Content-Type", "text/xml");
    response.write(
      `<?xml version="1.0" encoding="UTF-8"?>
         <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          ${Array.from({ length: sitemaps }, (_, index) => index + 1)
        .map(
          (pageNumber) =>
            `<loc>${BASE_URL}/${pattern.replace(
              `${pageNumber}`,
              pageNumber.toString()
            )}</loc>`
        )
        .join("")}
                   </sitemapindex>`
    );
    response.end();
  }
};

export const setPaginatedSitemapXML = async (
  response: ServerResponse,
  endpoint: string,
  path: string,
  namespace: string,
  pageNumber: string,
  request: any
) => {
  const newPath = `${path}?${namespace}:page=${pageNumber}&${namespace}:limit=1`;
  return setSitemapXML(response, endpoint, newPath, namespace, request);
};
